services:
  nuget-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nuget-server:latest
    container_name: nuget-server
    ports:
      - "8080:80"
    environment:
      # API Key for package publishing (leave empty for no authentication)
      - NUGET_API_KEY=${NUGET_API_KEY:-}
      
      # Path where packages are stored inside the container
      - NUGET_PACKAGES_PATH=C:\Packages
      
      # Allow overwriting existing packages (true/false)
      - NUGET_ALLOW_OVERWRITE_EXISTING_PACKAGE_ON_PUSH=false
      
      # Enable delisting instead of deletion (true/false)
      - NUGET_ENABLE_DELISTING=false
    volumes:
      # Persist packages across container restarts
      - nuget-packages:C:\Packages
    restart: unless-stopped

volumes:
  nuget-packages:
    driver: local
