services:
  nuget-server:
    build:
      context: .
      dockerfile: Dockerfile.mono
    image: nuget-server:mono
    container_name: nuget-server-mono
    ports:
      - "8080:8080"
    environment:
      # API Key for package publishing (leave empty for no authentication)
      - NUGET_API_KEY=${NUGET_API_KEY:-}
      
      # Path where packages are stored inside the container
      - NUGET_PACKAGES_PATH=/var/nuget/packages
      
      # Allow overwriting existing packages (true/false)
      - NUGET_ALLOW_OVERWRITE_EXISTING_PACKAGE_ON_PUSH=false
      
      # Enable delisting instead of deletion (true/false)
      - NUGET_ENABLE_DELISTING=false
      
      # Port for the ASP.NET server
      - ASPNET_PORT=8080
    volumes:
      # Persist packages across container restarts
      - nuget-packages:/var/nuget/packages
    restart: unless-stopped

volumes:
  nuget-packages:
    driver: local
